<?php
/**
 * @file
 * @author: William Panting
 * This is the global code for islandora_image_to_HTML_img_viewer
 */

/**
 * This function is the hook into the 'islandora viewer sphere'.
 *
 * It reports that this module can handle some image mime types and the theme
 * function to call to use it.
 *
 * @param string $mime_type
 *   The mime_type that is being queried for
 *
 * @return mixed
 *   array: 'mimetype'=>'theme to call'
 *   string : 'islandora_image_to_HTML_img'
 */
function islandora_image_to_HTML_img_viewer_islandora_viewers($mime_type = NULL) {
  if ($mime_type == NULL) {
    return array(
      'image/jpeg' => 'islandora_image_to_HTML_img',
      'image/png' => 'islandora_image_to_HTML_img',
    );
  }
  elseif ($mime_type == 'application/xml') {
    return 'islandora_image_to_HTML_img';
  }
}

/**
 * This function makes available the islandora_image_to_HTML_img theme.
 *
 * The theme will display an HTML unordered list
 *
 * @return array
 *   the themes available from this module
 */
function islandora_image_to_HTML_img_viewer_theme() {
  return array(
    'islandora_image_to_HTML_img' => array(
      'variables' => array(
        'pid' => NULL,
        'dsid' => 'JPG',
      ),
      'template' => 'islandora_image_to_HTML_img',
    ),
  );
}

/**
 * Preprocessor function that prepares image data as an HTML image tag.
 *
 * It will take the image data and put it in a variable.
 *
 * @param array $vars
 *   The variables to prepare for themeing
 */
function islandora_image_to_HTML_img_viewer_preprocess_islandora_image_to_HTML_img(&$vars) {
  $pid = $vars['pid'];
  $dsid = $vars['dsid'];

  drupal_add_css(drupal_get_path('module', 'islandora_image_to_HTML_img_viewer') . '/css/viewer.css');

  $params = array(
      'path' => "islandora/object/" . $pid . "/datastream/" . $dsid . "/view",
      'width' => '100%',
       'attributes' => array()
  );
  $image_markup = theme_image($params);
  $vars['image_datastream'] = $image_markup;
}
